name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: chmod +x appconfig/startscript
      - run: tar cvzf appconfig.tgz appconfig/

      - uses: actions/upload-artifact@v2
        with:
          name: appconfig.tgz
          path: appconfig.tgz
